//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        public string CMND_CCCD { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string MABENHNHAN { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string GIUONGBENH { get; set; }
        public Nullable<System.DateTime> NGNHAPVIEN { get; set; }
        public string QUOCTICH { get; set; }
        public string GHICHU { get; set; }
        public string TINHTRANG { get; set; }
        public string BENHNEN { get; set; }
        public Nullable<int> IDPHONG { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
