//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.PHONGs = new HashSet<PHONG>();
            this.VATTUs = new HashSet<VATTU>();
        }
    
        public string CMND_CCCD { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string MABENHNHAN { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string GIUONGBENH { get; set; }
        public Nullable<System.DateTime> NGNHAPVIEN { get; set; }
        public string QUOCTICH { get; set; }
        public string GHICHU { get; set; }
        public string TINHTRANG { get; set; }
        public string BENHNEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VATTU> VATTUs { get; set; }
    }
}
