//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGVIEC()
        {
            this.BACSILIENQUANs = new HashSet<BACSILIENQUAN>();
            this.YTALIENQUANs = new HashSet<YTALIENQUAN>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDTO { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> BATDAU { get; set; }
        public Nullable<System.DateTime> KETTHUC { get; set; }
        public string DIADIEM { get; set; }
        public string TINHCHAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BACSILIENQUAN> BACSILIENQUANs { get; set; }
        public virtual TO TO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YTALIENQUAN> YTALIENQUANs { get; set; }
    }
}
