CREATE DATABASE QUANLYBENHVIEN
GO
USE QUANLYBENHVIEN
GO
CREATE TABLE BACSI (
	CMND_CCCD	NVARCHAR(100) PRIMARY KEY,
	HO			NVARCHAR(100),
	TEN			NVARCHAR(100),
	SDT			VARCHAR(20),
	EMAIL		NVARCHAR(100),
	QUOCTICH	NVARCHAR(100),
	DIACHI		NVARCHAR(MAX),
	NGSINH		SMALLDATETIME,
	GIOITINH	BIT,
	VAITRO		NVARCHAR(100),
	CHUYENKHOA	NVARCHAR(100),
	GHICHU		NVARCHAR(MAX),
	IDTO		INT
)
GO
CREATE TABLE YTA (
	CMND_CCCD	NVARCHAR(100) PRIMARY KEY,
	HO			NVARCHAR(100),
	TEN			NVARCHAR(100),
	SDT			VARCHAR(20),
	EMAIL		NVARCHAR(100),
	QUOCTICH	NVARCHAR(100),
	DIACHI		NVARCHAR(MAX),
	NGSINH		SMALLDATETIME,
	GIOITINH	BIT,
	VAITRO		NVARCHAR(100),
	CHUYENKHOA	NVARCHAR(100),
	GHICHU		NVARCHAR(MAX),
	IDTO		INT
)
GO
CREATE TABLE [TO] (
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	IDTANG		INT
)
GO
CREATE TABLE TANG (
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	SOTANG		INT,
	SLPHONG		INT
)
GO
CREATE TABLE PHONG (
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	SOPHONG		INT,
	SUCCHUA	INT,
	GHICHU		NVARCHAR(MAX),
	IDTANG		INT
)
GO
CREATE TABLE BENHNHAN (
	CMND_CCCD	NVARCHAR(100) PRIMARY KEY,
	HO			NVARCHAR(100),
	TEN			NVARCHAR(100),
	MABENHNHAN	NVARCHAR(20),
	SDT			VARCHAR(20),
	EMAIL		NVARCHAR(100),
	DIACHI		NVARCHAR(MAX),
	NGSINH		SMALLDATETIME,
	GIOITINH	BIT,
	GIUONGBENH	NVARCHAR(20),
	NGNHAPVIEN	SMALLDATETIME,
	QUOCTICH	NVARCHAR(100),
	GHICHU		NVARCHAR(MAX),
	TINHTRANG	NVARCHAR(MAX),
	BENHNEN		NVARCHAR(MAX),
)
GO
CREATE TABLE [USER] (
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME	NVARCHAR(100),
	[PASSWORD]	NVARCHAR(32),
)
GO
--Thêm ràng buộc
--BACSI
ALTER TABLE BACSI ADD CONSTRAINT BACSI_IDTO_FK FOREIGN KEY (IDTO) REFERENCES [TO](ID)
--YTA
ALTER TABLE YTA ADD CONSTRAINT YTA_IDTO_FK FOREIGN KEY (IDTO) REFERENCES [TO](ID)
--TO
ALTER TABLE [TO] ADD CONSTRAINT TO_IDTANG_FK FOREIGN KEY (IDTANG) REFERENCES [TANG](ID)
--PHONG
ALTER TABLE PHONG ADD CONSTRAINT PHONG_IDTANG_FK FOREIGN KEY (IDTANG) REFERENCES [TANG](ID)
--BENHNHAN
ALTER TABLE BENHNHAN ADD IDPHONG INT
ALTER TABLE BENHNHAN ADD CONSTRAINT BENHNHAN_IDPHONG_FK FOREIGN KEY (IDPHONG) REFERENCES [PHONG](ID)
GO
--Mối kết hợp 
CREATE TABLE TOA (
	IDTOA		INT IDENTITY(1,1),
	SOTOA		INT,
	DISPLAYNAME NVARCHAR(100),
	SLTANG		INT
	CONSTRAINT TOA_PK PRIMARY KEY (IDTOA)
)
GO

ALTER TABLE TANG ADD
	IDTOA INT,
	CONSTRAINT TANG_IDTOA_FK FOREIGN KEY (IDTOA) REFERENCES TOA(IDTOA)
GO
--ALTER TABLE [TO] ADD
--	IDTOTRUONG NVARCHAR(100),
--	IDUSER INT,
--	CONSTRAINT TO_USER_FK FOREIGN KEY (IDUSER) REFERENCES [USER](ID),
--	CONSTRAINT TO_BACSI_FK FOREIGN KEY (IDTOTRUONG) REFERENCES BACSI(CMND_CCCD)
--GO
ALTER TABLE YTA ADD
	IDUSER INT,
	CONSTRAINT YTA_USER_FK FOREIGN KEY (IDUSER) REFERENCES [USER](ID)
GO
ALTER TABLE BACSI ADD
	IDUSER INT,
	CONSTRAINT BACSI_USER_FK FOREIGN KEY (IDUSER) REFERENCES [USER](ID)
GO
ALTER TABLE [USER] ADD [ROLE] NVARCHAR(100)
GO
CREATE TABLE [ADMIN](
	ID			NVARCHAR(100) PRIMARY KEY,
	IDUSER		INT,
	HO			NVARCHAR(100),
	TEN			NVARCHAR(100),
	EMAIL		NVARCHAR(100),
	SDT			VARCHAR(20),
	NGSINH		SMALLDATETIME,
	GIOITINH	BIT,
	QUOCTICH	NVARCHAR(100),
	DIACHI		NVARCHAR(MAX),
	CONSTRAINT ADMIN_USER_FK FOREIGN KEY (IDUSER) REFERENCES [USER](ID)
)
GO
INSERT INTO [USER] (USERNAME, [PASSWORD], [ROLE]) VALUES ('superadmin', '57C8A760C897A1340E9290CEF621D94B', 'sudo')
GO

CREATE TABLE CONGVIEC
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDTO INT,
	TIEUDE NVARCHAR(256),
	NOIDUNG NVARCHAR(MAX),
	BATDAU SMALLDATETIME,
	KETTHUC SMALLDATETIME,
	DIADIEM NVARCHAR(1024),
	TINHCHAT NVARCHAR(256),
	CONSTRAINT CONVIEC_TO_FK FOREIGN KEY (IDTO) REFERENCES [TO](ID)
)
GO
CREATE TABLE BACSILIENQUAN
(
	IDCONGVIEC INT,
	CMND_CCCD NVARCHAR(100),
	TIENDO BIT,
	CONSTRAINT BACSILIENQUAN_PK PRIMARY KEY (IDCONGVIEC, CMND_CCCD),
	CONSTRAINT BACSILIENQUAN_CONGVIEC_FK FOREIGN KEY (IDCONGVIEC) REFERENCES CONGVIEC(ID),
	CONSTRAINT BACSILIENQUAN_BACSI_FK FOREIGN KEY (CMND_CCCD) REFERENCES BACSI(CMND_CCCD)
)

GO
CREATE TABLE YTALIENQUAN
(
	IDCONGVIEC INT,
	CMND_CCCD NVARCHAR(100),
	TIENDO BIT,
	CONSTRAINT YTALIENQUAN_PK PRIMARY KEY (IDCONGVIEC, CMND_CCCD),
	CONSTRAINT YTALIENQUAN_CONGVIEC_FK FOREIGN KEY (IDCONGVIEC) REFERENCES CONGVIEC(ID),
	CONSTRAINT YTALIENQUAN_YTA_FK FOREIGN KEY (CMND_CCCD) REFERENCES YTA(CMND_CCCD)
)

GO
