//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeds
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public string ID { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
