//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeds
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYBENHVIENEntities : DbContext
    {
        public QUANLYBENHVIENEntities()
            : base("name=QUANLYBENHVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<BACSI> BACSIs { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<TANG> TANGs { get; set; }
        public virtual DbSet<TO> TOes { get; set; }
        public virtual DbSet<TOA> TOAs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<VATTU> VATTUs { get; set; }
        public virtual DbSet<YTA> YTAs { get; set; }
    }
}
