//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeds
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VATTU()
        {
            this.TOes = new HashSet<TO>();
            this.BENHNHANs = new HashSet<BENHNHAN>();
        }
    
        public int ID { get; set; }
        public string DISPLAYNAME { get; set; }
        public string LOAIVATTU { get; set; }
        public Nullable<System.DateTime> NGSX { get; set; }
        public Nullable<int> SLUONG { get; set; }
        public string DVTINH { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO> TOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENHNHAN> BENHNHANs { get; set; }
    }
}
